### ISSUE TITLE
### Angular Site Home Basic Setup

### ISSUE THREAD

**Issue by IanKorkie** [IanKorkie/TimeMe#43]
## Tasks
 - [x] Must I have a seperate module for the dashboard
 - [x] Create component structure
 - [x] Create logo and replace old logo
 - [x] Import Bootstrap Module
